/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RidesRouteImport } from './routes/rides'
import { Route as PlanTripRouteImport } from './routes/plan-trip'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as ItinerariesRouteImport } from './routes/itineraries'
import { Route as HotelsRouteImport } from './routes/hotels'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as EntertainmentRouteImport } from './routes/entertainment'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RidesRoute = RidesRouteImport.update({
  id: '/rides',
  path: '/rides',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanTripRoute = PlanTripRouteImport.update({
  id: '/plan-trip',
  path: '/plan-trip',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ItinerariesRoute = ItinerariesRouteImport.update({
  id: '/itineraries',
  path: '/itineraries',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsRoute = HotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const EntertainmentRoute = EntertainmentRouteImport.update({
  id: '/entertainment',
  path: '/entertainment',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/booking': typeof BookingRoute
  '/entertainment': typeof EntertainmentRoute
  '/feedback': typeof FeedbackRoute
  '/hotels': typeof HotelsRoute
  '/itineraries': typeof ItinerariesRoute
  '/payments': typeof PaymentsRoute
  '/plan-trip': typeof PlanTripRoute
  '/rides': typeof RidesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/booking': typeof BookingRoute
  '/entertainment': typeof EntertainmentRoute
  '/feedback': typeof FeedbackRoute
  '/hotels': typeof HotelsRoute
  '/itineraries': typeof ItinerariesRoute
  '/payments': typeof PaymentsRoute
  '/plan-trip': typeof PlanTripRoute
  '/rides': typeof RidesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/booking': typeof BookingRoute
  '/entertainment': typeof EntertainmentRoute
  '/feedback': typeof FeedbackRoute
  '/hotels': typeof HotelsRoute
  '/itineraries': typeof ItinerariesRoute
  '/payments': typeof PaymentsRoute
  '/plan-trip': typeof PlanTripRoute
  '/rides': typeof RidesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/booking'
    | '/entertainment'
    | '/feedback'
    | '/hotels'
    | '/itineraries'
    | '/payments'
    | '/plan-trip'
    | '/rides'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/booking'
    | '/entertainment'
    | '/feedback'
    | '/hotels'
    | '/itineraries'
    | '/payments'
    | '/plan-trip'
    | '/rides'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/booking'
    | '/entertainment'
    | '/feedback'
    | '/hotels'
    | '/itineraries'
    | '/payments'
    | '/plan-trip'
    | '/rides'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  BookingRoute: typeof BookingRoute
  EntertainmentRoute: typeof EntertainmentRoute
  FeedbackRoute: typeof FeedbackRoute
  HotelsRoute: typeof HotelsRoute
  ItinerariesRoute: typeof ItinerariesRoute
  PaymentsRoute: typeof PaymentsRoute
  PlanTripRoute: typeof PlanTripRoute
  RidesRoute: typeof RidesRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rides': {
      id: '/rides'
      path: '/rides'
      fullPath: '/rides'
      preLoaderRoute: typeof RidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-trip': {
      id: '/plan-trip'
      path: '/plan-trip'
      fullPath: '/plan-trip'
      preLoaderRoute: typeof PlanTripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itineraries': {
      id: '/itineraries'
      path: '/itineraries'
      fullPath: '/itineraries'
      preLoaderRoute: typeof ItinerariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels': {
      id: '/hotels'
      path: '/hotels'
      fullPath: '/hotels'
      preLoaderRoute: typeof HotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entertainment': {
      id: '/entertainment'
      path: '/entertainment'
      fullPath: '/entertainment'
      preLoaderRoute: typeof EntertainmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  BookingRoute: BookingRoute,
  EntertainmentRoute: EntertainmentRoute,
  FeedbackRoute: FeedbackRoute,
  HotelsRoute: HotelsRoute,
  ItinerariesRoute: ItinerariesRoute,
  PaymentsRoute: PaymentsRoute,
  PlanTripRoute: PlanTripRoute,
  RidesRoute: RidesRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
